security:
    firewalls:
        main:
            anonymous: true
            lazy: true
            logout: ~
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
                entry_point: App\Security\TokenAuthenticator
            json_login:
                check_path: /login
    providers:
        your_db_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    access_control:
        #- { path: ^/categoria }
        #- { path: ^/contacto }
        #- { path: ^/proyecto }
        # - { path: ^/profile, roles: ROLE_USER }
