<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEk1x1Qf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEk1x1Qf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEk1x1Qf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEk1x1Qf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEk1x1Qf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ek1x1Qf',
    'container.build_id' => 'ae4eee7e',
    'container.build_time' => 1612307125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEk1x1Qf');
