<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjluWy0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjluWy0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTjluWy0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTjluWy0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTjluWy0\App_KernelDevDebugContainer([
    'container.build_hash' => 'TjluWy0',
    'container.build_id' => 'aab4b98e',
    'container.build_time' => 1612865853,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjluWy0');
