<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAntpfkC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAntpfkC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAntpfkC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAntpfkC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAntpfkC\App_KernelDevDebugContainer([
    'container.build_hash' => 'AntpfkC',
    'container.build_id' => '94ddc1ea',
    'container.build_time' => 1612809276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAntpfkC');
