<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'categoriaaddCategoria' => [[], ['_controller' => 'App\\Controller\\CategoriaController::addCategoria'], [], [['text', '/categoria/addCategoria']], [], []],
    'categoriagetCategoria' => [['id'], ['_controller' => 'App\\Controller\\CategoriaController::getCategoria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categoria/getCategoria']], [], []],
    'categoriagetCategorias' => [[], ['_controller' => 'App\\Controller\\CategoriaController::getCategorias'], [], [['text', '/categoria/getCategorias']], [], []],
    'categoriaupdateCategoria' => [['id'], ['_controller' => 'App\\Controller\\CategoriaController::editCategoria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categoria/updateCategoria']], [], []],
    'categoriadeleteCategoria' => [['id'], ['_controller' => 'App\\Controller\\CategoriaController::deleteCategoria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categoria/deleteCategoria']], [], []],
    'contactoaddContacto' => [[], ['_controller' => 'App\\Controller\\ContactoController::addContacto'], [], [['text', '/contacto/addContacto']], [], []],
    'contactogetContacto' => [['id'], ['_controller' => 'App\\Controller\\ContactoController::getContacto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contacto/getContacto']], [], []],
    'contactogetContactos' => [[], ['_controller' => 'App\\Controller\\ContactoController::getContactos'], [], [['text', '/contacto/getContactos']], [], []],
    'contactogetContactosEntreDosFechas' => [[], ['_controller' => 'App\\Controller\\ContactoController::getContactosEntreDosFechas'], [], [['text', '/contacto/getContactosEntreDosFechas/{fecha1,fecha2}']], [], []],
    'contactoupdateContacto' => [['id'], ['_controller' => 'App\\Controller\\ContactoController::editContacto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contacto/updateContacto']], [], []],
    'contactodeleteContacto' => [['id'], ['_controller' => 'App\\Controller\\ContactoController::deleteContacto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/contacto/deleteContacto']], [], []],
    'proyectoaddProyecto' => [[], ['_controller' => 'App\\Controller\\ProyectoController::addProyecto'], [], [['text', '/proyecto/addProyecto']], [], []],
    'proyectogetProyecto' => [['id'], ['_controller' => 'App\\Controller\\ProyectoController::getProyecto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/proyecto/getProyecto']], [], []],
    'proyectogetProyectos' => [[], ['_controller' => 'App\\Controller\\ProyectoController::getProyectos'], [], [['text', '/proyecto/getProyectos']], [], []],
    'proyectogetProyectosConCategoria' => [['id'], ['_controller' => 'App\\Controller\\ProyectoController::getProyectosConCategoria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/proyecto/getProyectosConCategoria']], [], []],
    'proyectoupdateProyecto' => [['id'], ['_controller' => 'App\\Controller\\ProyectoController::editProyecto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/proyecto/updateProyecto']], [], []],
    'proyectodeleteProyecto' => [['id'], ['_controller' => 'App\\Controller\\ProyectoController::deleteProyecto'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/proyecto/deleteProyecto']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'usuarioaddUsuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::addUsuario'], [], [['text', '/usuario/addUsuario']], [], []],
    'usuariogetUsuario' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::getUsuario'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/usuario/getUsuario']], [], []],
    'usuariogetUsuarios' => [[], ['_controller' => 'App\\Controller\\UsuarioController::getUsuarios'], [], [['text', '/usuario/getUsuarios']], [], []],
    'usuariogetUsuariosConCategoria' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::getUsuariosConCategoria'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/usuario/getUsuariosConCategoria']], [], []],
    'usuarioupdateUsuario' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::editUsuario'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/usuario/updateUsuario']], [], []],
    'usuariodeleteUsuario' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::deleteUsuario'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/usuario/deleteUsuario']], [], []],
];
